cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__common_cells_1.16.4/src/addr_decode.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__common_cells_1.16.4/src/delta_counter.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__common_cells_1.16.4/src/fifo_v3.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__common_cells_1.16.4/src/rr_arb_tree.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__common_cells_1.16.4/src/spill_register.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__common_cells_1.16.4/src/counter.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__common_cells_1.16.4/src/stream_register.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__common_cells_1.16.4/src/deprecated/fifo_v2.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__axi_0.23.0-r1/include/axi/assign.svh /home/altus/Cores-biriscv-AltuSOC/rtl/axi/include/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__axi_0.23.0-r1/include/axi/typedef.svh /home/altus/Cores-biriscv-AltuSOC/rtl/axi/include/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__common_cells_1.16.4/include/common_cells/registers.svh /home/altus/Cores-biriscv-AltuSOC/rtl/axi/include/common_cells/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__axi_0.23.0-r1/src/axi_pkg.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__axi_0.23.0-r1/src/axi_atop_filter.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__axi_0.23.0-r1/src/axi_demux.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__axi_0.23.0-r1/src/axi_id_prepend.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__axi_0.23.0-r1/src/axi_mux.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__axi_0.23.0-r1/src/axi_err_slv.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp  /home/altus/swervolf/build/altusoc_0.1/src/pulp-platform.org__axi_0.23.0-r1/src/axi_xbar.sv /home/altus/Cores-biriscv-AltuSOC/rtl/axi/
cp /home/altus/swervolf/build/altusoc_0.1/src/wb_intercon_1.2.2-r1/rtl/verilog/wb_mux.v /home/altus/Cores-biriscv-AltuSOC/rtl/wb/
cp  /home/altus/swervolf/build/altusoc_0.1/src/altusoc-intercon_0.1/axi_intercon.v /home/altus/Cores-biriscv-AltuSOC/rtl/axi/include/
cp /home/altus/swervolf/build/altusoc_0.1/src/altusoc-wb_intercon_0.1/wb_intercon.v /home/altus/Cores-biriscv-AltuSOC/rtl/wb/include/
